### ISSUE TITLE
Attach circleci workspace and set terraform workspace

### ISSUE THREAD

**Issue by amioranza** [infracost/infracost-orb#5]
Hi,

#1
I'm trying to use this orb but my project uses some private repositories for terraform modules and the infracost cannot handle it even with the github token to access the repos, so I'm trying to attach the workspace from the previous steps to run the infracost over the terraform plan but it does not have support to attach the circleci workspace too. 

#2
I need to pass the terraform workspace for the terraform, is this syntax right?

```
- infracost/infracost:
     tfdir: '.'
     tfflags: '-var environment=staging'
```

Thanks.

**Comment by alikhajeh1** [comment]
@amioranza so the orb just run [this](https://github.com/infracost/infracost-orb/blob/master/src/%40orb.yml#L7-L49) so one thing you can try is to just set the following in your `.circleci/config.yml` to fix #2 (TF_WORKSPACE is a built-in terraform env var). Regarding #1, I wonder if the following helps as it's a circleci `job` so it can be used in your existing workflow so it shares the workspace?

```
jobs:
  infracost:
    docker:
      - image: infracost/infracost:latest
    environment:
      percentage_threshold: '0'
      tfdir: '.'
      tfflags: '-var environment=staging'
      TF_WORKSPACE: staging
    steps:
      - checkout
      - run: /scripts/ci/diff.sh
```
